### ISSUE TITLE
Converting to Budgie

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-control-center#1]
Task list for the remaining parts of the conversion to be done before we can start testing etc.  Anyone welcome to dive in for any of this/add to etc.

- [x] polkit stuff - rename to be budgie
- [x] look at the gnome/its stuff - is this needed?
- [x] Merge in various commits from the GNOME 41 branch https://gitlab.gnome.org/GNOME/gnome-control-center/-/commits/gnome-41
- [x] Look to see why compilation throws i18 deprecated notices - maybe this? https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/37b29c32cbecfd89c9c5e0169e0f2876f00ef5eb
- [x] Debian packaging for GNOME Control Center has a number of patches  - why are they not upstream?  Are they useful for all budgie users?
- [x] Ubuntu packaging for GNOME Control Center has a number of patches  - why are they not upstream?  Are they useful for all budgie users?
- [x] Create debian package for budgie-control-center and see if both gnome-control-center and budgie-control-center will install simultaneously - this will help identify what areas still need to be 'budgied' - Package partially done.

**Comment by JoshStrobl** [comment]
> look at the gnome/its stuff - is this needed?´

Depends on what you mean specifically. I already stripped out their Search panel, which is for their search provider bits in GNOME Shell, as well as the GNOME Shell-specific workspace functionality. Is there anything else you think we missed? Going through it per panel, this is what I see:

- Network: Applicable
- Bluetooth: Applicable
- Background: Applicable
- Notifications: We check this for notifications & Raven
- Applications: Applicable because it exposes default handlers, notifications, flatpak settings (I think?)
- Privacy: Applicable
- Online Accounts: Applicable
- Sharing: Useful for screensharing but can't say I've used this on Budgie. Maybe can be removed?
- Sound: Applicable
- Power: Applicable
- Displays: Applicable. IIRC Ubuntu has a patch for more scaling options, maybe worth looking at.
- Mouse & Touchpad: Applicable
- Keyboard: Applicable
- Printers: Applicable
- Removable Media: Applicable
- Color: Applicable
- Region & Language: Applicable
- Accessibility: Likely depends on an individual setting and dependent on any defaults shipped by the OS
- Users: Applicable
- Default Applications: Applicable
- Date & Time: Applicable
- About: Applicable but should ensure we replace the GNOME logo fallback with Budgie, and double check that distros can have their logo. I patched that for a long time in Solus but having something more agnostic would be preferable. `GNOME Version` should probably be swapped for `Budgie Version` or added above it so we know what GNOME stack they are on.

**Comment by fossfreedom** [comment]
the gnome - its stuff I am referring to is this bit https://github.com/BuddiesOfBudgie/budgie-control-center/tree/master/gettext/its

Re the logo - yeah - I spotted something on the debian patching where they mentioned a vendor neutral patch for logo etc.  I'll dig that out and see what they are specifically referring to.
