### ISSUE TITLE
Changing the name 

### ISSUE THREAD

**Issue by Triplesweet** [BuddiesOfBudgie/budgie-control-center#36]
In my opinion budgie control center is not a good name for 3 reasons

1. It is longet than what it should be imo considering some DEs and even windows just use settings
2. When someone wants to open the settings app it is a muscle memory to press the super key and write settings, but budgie control center doesn't have setting in its name so it doesn't show and makes the person a little annoyed (it does for me at least)
3.  and budgie control center feels more like an app that controls budgie DE itself rather than the system, after all it is mostly settings for hardware of the system than software side that budgie will interact

In my opinion you can rename the apps to system settings and desktop settings, I feel this will be easier to understand and solve the search problems as well

**Comment by fossfreedom** [comment]
I don't support the idea. It should be easier to navigate to one or the other which 10.7 brings via the menu ui change. 

Budgie 11 will introduce the idea of "one rules then all" rather than the odd case of two at the moment.

What would be better then worrying about the name is easier to navigate to the right section on both desktop settings and control center via the menu. 

E.g. typing panel should navigate to budgie desktop settings - panel as a highlighted section, whereas display should open the displays section in control center.  Such an enhancement would need changes in the desktop project as well as this one to provide the data for desktop.

**Comment by Triplesweet** [comment]
With the improvements the budgie menu gets in 10.7 does fix the problem in one aspect, but not in aspect of "keyboard only" imo. 

And for budgie 11, we do t know when they will start the development and when it will be for the public, and relying and imo changing the name till the new settings app is developed can be helpful (unless the  " one rule then all" means something else, I would appreciate if you tell me if I'm wrong to correct myself)

**Comment by serebit** [comment]
I'm not a huge fan of the name of Budgie Control Center, but I don't think changing it now would be wise given that it's already been released and we're a few versions in. I do think that adding "settings" to the app description would be a good idea, since it would then get picked up by the search in Budgie Menu when the word is typed.

**Comment by Triplesweet** [comment]
I still believe it will be a small but nice touch to change the name but, Since we need to think of the devs too, if changing the name takes longer than max one hour or the 11x is coming sooner, then yes it is indeed not worth it.
