### ISSUE TITLE
Dependency Gnome-Control-Center

### ISSUE THREAD

**Issue by fugo** [BuddiesOfBudgie/budgie-control-center#47]
### Current budgie-control-center version
`budgie-control-center 1.1.1`
`budgie-desktop 10.6.4`
`Arch Linux`
I use gnome-calendar with my Nextcloud and want to get rid of gnome-control-center but gnome-calendar has this dependency.

Can this be solved?
Or is there a plan for a Budgie calendar with Nextcloud support?

TIA
I use Budgie now some years and it's great that Budgie is no longer just focused on Solus. :+1:

**Comment by serebit** [comment]
This isn't something we can resolve on the B-C-C end, because what you're reporting is an issue with GNOME Calendar or Arch Linux's packaging of it. There's no way for us to mandate that GNOME Calendar avoid a dependency on GNOME Control Center. However, in the process of looking into this, I did discover that the Budgie Menu isn't hiding some apps that it should be hiding - including GNOME Control Center. That is to say, I can't stop GNOME Calendar from depending on GNOME Control Center, but I can patch the Budgie Menu to avoid showing it.

**Comment by fugo** [comment]
Hiding the double entries would be good for now.
Thank you.

**Comment by fossfreedom** [comment]
@fugo I looked at the Debian packaging of gnome-calendar and there is no linkage to gnome-control-center.

https://packages.debian.org/sid/gnome-calendar

So I would raise a bug on Arch to discuss why there is a dependency on gnome-control-center.

**Comment by serebit** [comment]
Yeah, I would recommend creating an issue on the Arch bug tracker: https://bugs.archlinux.org/
